version: "2"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: andrew
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
  api:
    container_name: api
    build: ./api/
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://andrew:password@db:5432/movies
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - ./api:/api
